
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 08 06:18:00 CEST 2016
//----------------------------------------------------

package rs.ac.bg.etf.pp1.sm120554d;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 43;
  public static final int OBRAC = 13;
  public static final int CONST = 5;
  public static final int OCBRAC = 3;
  public static final int GRT = 31;
  public static final int SC = 8;
  public static final int LSS = 33;
  public static final int MINUS = 26;
  public static final int STR_CONST = 44;
  public static final int AND = 25;
  public static final int CBRAC = 14;
  public static final int OR = 24;
  public static final int COMMA = 7;
  public static final int CLASS = 11;
  public static final int INC = 21;
  public static final int DIV = 37;
  public static final int ASSIGN = 6;
  public static final int IF = 16;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int CSBRAC = 10;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 36;
  public static final int PERCENT = 38;
  public static final int ADD = 35;
  public static final int NUMBER = 41;
  public static final int IDENT = 40;
  public static final int BREAK = 17;
  public static final int VOID = 15;
  public static final int EQU = 29;
  public static final int NEQU = 30;
  public static final int ELSE = 23;
  public static final int OSBRAC = 9;
  public static final int POINT = 28;
  public static final int READ = 19;
  public static final int WHILE = 39;
  public static final int EXTENDS = 12;
  public static final int GEQU = 32;
  public static final int BOOL_CONST = 42;
  public static final int LEQU = 34;
  public static final int CCBRAC = 4;
  public static final int DEC = 22;
  public static final int PRINT = 20;
}

